//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneAppSmartVigi.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtilisateurPhone", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSmartVigi")]
    public partial class UtilisateurPhone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresseField;
        
        private string EmailField;
        
        private int IDField;
        
        private string LoginField;
        
        private string NTelField;
        
        private string NomField;
        
        private string PasswordField;
        
        private string PrenomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NTel {
            get {
                return this.NTelField;
            }
            set {
                if ((object.ReferenceEquals(this.NTelField, value) != true)) {
                    this.NTelField = value;
                    this.RaisePropertyChanged("NTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepertoirePhone", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSmartVigi")]
    public partial class RepertoirePhone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresseField;
        
        private string EmailField;
        
        private int IDContactField;
        
        private int IDUtilisateurField;
        
        private string NTelField;
        
        private string NomField;
        
        private string PrenomField;
        
        private int PrioriteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresse {
            get {
                return this.AdresseField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresseField, value) != true)) {
                    this.AdresseField = value;
                    this.RaisePropertyChanged("Adresse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDContact {
            get {
                return this.IDContactField;
            }
            set {
                if ((this.IDContactField.Equals(value) != true)) {
                    this.IDContactField = value;
                    this.RaisePropertyChanged("IDContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUtilisateur {
            get {
                return this.IDUtilisateurField;
            }
            set {
                if ((this.IDUtilisateurField.Equals(value) != true)) {
                    this.IDUtilisateurField = value;
                    this.RaisePropertyChanged("IDUtilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NTel {
            get {
                return this.NTelField;
            }
            set {
                if ((object.ReferenceEquals(this.NTelField, value) != true)) {
                    this.NTelField = value;
                    this.RaisePropertyChanged("NTel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priorite {
            get {
                return this.PrioriteField;
            }
            set {
                if ((this.PrioriteField.Equals(value) != true)) {
                    this.PrioriteField = value;
                    this.RaisePropertyChanged("Priorite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterventionDto", Namespace="http://schemas.datacontract.org/2004/07/BLL")]
    public partial class InterventionDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DataField;
        
        private System.DateTime DateHeureField;
        
        private string GPSLocationField;
        
        private int IDContactField;
        
        private int IDUtilisateurField;
        
        private int UrgenceLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateHeure {
            get {
                return this.DateHeureField;
            }
            set {
                if ((this.DateHeureField.Equals(value) != true)) {
                    this.DateHeureField = value;
                    this.RaisePropertyChanged("DateHeure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GPSLocation {
            get {
                return this.GPSLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.GPSLocationField, value) != true)) {
                    this.GPSLocationField = value;
                    this.RaisePropertyChanged("GPSLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDContact {
            get {
                return this.IDContactField;
            }
            set {
                if ((this.IDContactField.Equals(value) != true)) {
                    this.IDContactField = value;
                    this.RaisePropertyChanged("IDContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUtilisateur {
            get {
                return this.IDUtilisateurField;
            }
            set {
                if ((this.IDUtilisateurField.Equals(value) != true)) {
                    this.IDUtilisateurField = value;
                    this.RaisePropertyChanged("IDUtilisateur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrgenceLevel {
            get {
                return this.UrgenceLevelField;
            }
            set {
                if ((this.UrgenceLevelField.Equals(value) != true)) {
                    this.UrgenceLevelField = value;
                    this.RaisePropertyChanged("UrgenceLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IServicePhone")]
    public interface IServicePhone {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhone/LoginPhone", ReplyAction="http://tempuri.org/IServicePhone/LoginPhoneResponse")]
        PhoneAppSmartVigi.ServiceReference.UtilisateurPhone LoginPhone(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServicePhone/LoginPhone", ReplyAction="http://tempuri.org/IServicePhone/LoginPhoneResponse")]
        System.IAsyncResult BeginLoginPhone(string login, string password, System.AsyncCallback callback, object asyncState);
        
        PhoneAppSmartVigi.ServiceReference.UtilisateurPhone EndLoginPhone(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhone/GetRepertoire", ReplyAction="http://tempuri.org/IServicePhone/GetRepertoireResponse")]
        PhoneAppSmartVigi.ServiceReference.RepertoirePhone[] GetRepertoire(int IDUtilisateur);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServicePhone/GetRepertoire", ReplyAction="http://tempuri.org/IServicePhone/GetRepertoireResponse")]
        System.IAsyncResult BeginGetRepertoire(int IDUtilisateur, System.AsyncCallback callback, object asyncState);
        
        PhoneAppSmartVigi.ServiceReference.RepertoirePhone[] EndGetRepertoire(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhone/DoIntervention", ReplyAction="http://tempuri.org/IServicePhone/DoInterventionResponse")]
        void DoIntervention(PhoneAppSmartVigi.ServiceReference.InterventionDto interv);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServicePhone/DoIntervention", ReplyAction="http://tempuri.org/IServicePhone/DoInterventionResponse")]
        System.IAsyncResult BeginDoIntervention(PhoneAppSmartVigi.ServiceReference.InterventionDto interv, System.AsyncCallback callback, object asyncState);
        
        void EndDoIntervention(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePhoneChannel : PhoneAppSmartVigi.ServiceReference.IServicePhone, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhoneAppSmartVigi.ServiceReference.UtilisateurPhone Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhoneAppSmartVigi.ServiceReference.UtilisateurPhone)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRepertoireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRepertoireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhoneAppSmartVigi.ServiceReference.RepertoirePhone[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhoneAppSmartVigi.ServiceReference.RepertoirePhone[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePhoneClient : System.ServiceModel.ClientBase<PhoneAppSmartVigi.ServiceReference.IServicePhone>, PhoneAppSmartVigi.ServiceReference.IServicePhone {
        
        private BeginOperationDelegate onBeginLoginPhoneDelegate;
        
        private EndOperationDelegate onEndLoginPhoneDelegate;
        
        private System.Threading.SendOrPostCallback onLoginPhoneCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRepertoireDelegate;
        
        private EndOperationDelegate onEndGetRepertoireDelegate;
        
        private System.Threading.SendOrPostCallback onGetRepertoireCompletedDelegate;
        
        private BeginOperationDelegate onBeginDoInterventionDelegate;
        
        private EndOperationDelegate onEndDoInterventionDelegate;
        
        private System.Threading.SendOrPostCallback onDoInterventionCompletedDelegate;
        
        public ServicePhoneClient() {
        }
        
        public ServicePhoneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePhoneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhoneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhoneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<LoginPhoneCompletedEventArgs> LoginPhoneCompleted;
        
        public event System.EventHandler<GetRepertoireCompletedEventArgs> GetRepertoireCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoInterventionCompleted;
        
        public PhoneAppSmartVigi.ServiceReference.UtilisateurPhone LoginPhone(string login, string password) {
            return base.Channel.LoginPhone(login, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginLoginPhone(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginPhone(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PhoneAppSmartVigi.ServiceReference.UtilisateurPhone EndLoginPhone(System.IAsyncResult result) {
            return base.Channel.EndLoginPhone(result);
        }
        
        private System.IAsyncResult OnBeginLoginPhone(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginLoginPhone(login, password, callback, asyncState);
        }
        
        private object[] OnEndLoginPhone(System.IAsyncResult result) {
            PhoneAppSmartVigi.ServiceReference.UtilisateurPhone retVal = this.EndLoginPhone(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginPhoneCompleted(object state) {
            if ((this.LoginPhoneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginPhoneCompleted(this, new LoginPhoneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginPhoneAsync(string login, string password) {
            this.LoginPhoneAsync(login, password, null);
        }
        
        public void LoginPhoneAsync(string login, string password, object userState) {
            if ((this.onBeginLoginPhoneDelegate == null)) {
                this.onBeginLoginPhoneDelegate = new BeginOperationDelegate(this.OnBeginLoginPhone);
            }
            if ((this.onEndLoginPhoneDelegate == null)) {
                this.onEndLoginPhoneDelegate = new EndOperationDelegate(this.OnEndLoginPhone);
            }
            if ((this.onLoginPhoneCompletedDelegate == null)) {
                this.onLoginPhoneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginPhoneCompleted);
            }
            base.InvokeAsync(this.onBeginLoginPhoneDelegate, new object[] {
                        login,
                        password}, this.onEndLoginPhoneDelegate, this.onLoginPhoneCompletedDelegate, userState);
        }
        
        public PhoneAppSmartVigi.ServiceReference.RepertoirePhone[] GetRepertoire(int IDUtilisateur) {
            return base.Channel.GetRepertoire(IDUtilisateur);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetRepertoire(int IDUtilisateur, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRepertoire(IDUtilisateur, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PhoneAppSmartVigi.ServiceReference.RepertoirePhone[] EndGetRepertoire(System.IAsyncResult result) {
            return base.Channel.EndGetRepertoire(result);
        }
        
        private System.IAsyncResult OnBeginGetRepertoire(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IDUtilisateur = ((int)(inValues[0]));
            return this.BeginGetRepertoire(IDUtilisateur, callback, asyncState);
        }
        
        private object[] OnEndGetRepertoire(System.IAsyncResult result) {
            PhoneAppSmartVigi.ServiceReference.RepertoirePhone[] retVal = this.EndGetRepertoire(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRepertoireCompleted(object state) {
            if ((this.GetRepertoireCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRepertoireCompleted(this, new GetRepertoireCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRepertoireAsync(int IDUtilisateur) {
            this.GetRepertoireAsync(IDUtilisateur, null);
        }
        
        public void GetRepertoireAsync(int IDUtilisateur, object userState) {
            if ((this.onBeginGetRepertoireDelegate == null)) {
                this.onBeginGetRepertoireDelegate = new BeginOperationDelegate(this.OnBeginGetRepertoire);
            }
            if ((this.onEndGetRepertoireDelegate == null)) {
                this.onEndGetRepertoireDelegate = new EndOperationDelegate(this.OnEndGetRepertoire);
            }
            if ((this.onGetRepertoireCompletedDelegate == null)) {
                this.onGetRepertoireCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRepertoireCompleted);
            }
            base.InvokeAsync(this.onBeginGetRepertoireDelegate, new object[] {
                        IDUtilisateur}, this.onEndGetRepertoireDelegate, this.onGetRepertoireCompletedDelegate, userState);
        }
        
        public void DoIntervention(PhoneAppSmartVigi.ServiceReference.InterventionDto interv) {
            base.Channel.DoIntervention(interv);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDoIntervention(PhoneAppSmartVigi.ServiceReference.InterventionDto interv, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoIntervention(interv, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndDoIntervention(System.IAsyncResult result) {
            base.Channel.EndDoIntervention(result);
        }
        
        private System.IAsyncResult OnBeginDoIntervention(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneAppSmartVigi.ServiceReference.InterventionDto interv = ((PhoneAppSmartVigi.ServiceReference.InterventionDto)(inValues[0]));
            return this.BeginDoIntervention(interv, callback, asyncState);
        }
        
        private object[] OnEndDoIntervention(System.IAsyncResult result) {
            this.EndDoIntervention(result);
            return null;
        }
        
        private void OnDoInterventionCompleted(object state) {
            if ((this.DoInterventionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoInterventionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoInterventionAsync(PhoneAppSmartVigi.ServiceReference.InterventionDto interv) {
            this.DoInterventionAsync(interv, null);
        }
        
        public void DoInterventionAsync(PhoneAppSmartVigi.ServiceReference.InterventionDto interv, object userState) {
            if ((this.onBeginDoInterventionDelegate == null)) {
                this.onBeginDoInterventionDelegate = new BeginOperationDelegate(this.OnBeginDoIntervention);
            }
            if ((this.onEndDoInterventionDelegate == null)) {
                this.onEndDoInterventionDelegate = new EndOperationDelegate(this.OnEndDoIntervention);
            }
            if ((this.onDoInterventionCompletedDelegate == null)) {
                this.onDoInterventionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoInterventionCompleted);
            }
            base.InvokeAsync(this.onBeginDoInterventionDelegate, new object[] {
                        interv}, this.onEndDoInterventionDelegate, this.onDoInterventionCompletedDelegate, userState);
        }
    }
}
