//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplicationSysDis.ServiceReferenceWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS/", ConfigurationName="ServiceReferenceWS.WSSoap")]
    public interface WSSoap {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSSoap/helloRequest", ReplyAction="http://WS/WSSoap/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplicationSysDis.ServiceReferenceWS.helloResponse hello(WpfApplicationSysDis.ServiceReferenceWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSSoap/helloRequest", ReplyAction="http://WS/WSSoap/helloResponse")]
        System.Threading.Tasks.Task<WpfApplicationSysDis.ServiceReferenceWS.helloResponse> helloAsync(WpfApplicationSysDis.ServiceReferenceWS.helloRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSSoap/PlayerDataRequest", ReplyAction="http://WS/WSSoap/PlayerDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WpfApplicationSysDis.ServiceReferenceWS.PlayerDataResponse PlayerData(WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS/WSSoap/PlayerDataRequest", ReplyAction="http://WS/WSSoap/PlayerDataResponse")]
        System.Threading.Tasks.Task<WpfApplicationSysDis.ServiceReferenceWS.PlayerDataResponse> PlayerDataAsync(WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class dataOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int playedField;
        
        private int winsField;
        
        private int lossesField;
        
        private partie[] partiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Played {
            get {
                return this.playedField;
            }
            set {
                this.playedField = value;
                this.RaisePropertyChanged("Played");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Wins {
            get {
                return this.winsField;
            }
            set {
                this.winsField = value;
                this.RaisePropertyChanged("Wins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int Losses {
            get {
                return this.lossesField;
            }
            set {
                this.lossesField = value;
                this.RaisePropertyChanged("Losses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public partie[] Parties {
            get {
                return this.partiesField;
            }
            set {
                this.partiesField = value;
                this.RaisePropertyChanged("Parties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class partie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateheureField;
        
        private bool dateheureFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private player player1Field;
        
        private player player2Field;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dateheure {
            get {
                return this.dateheureField;
            }
            set {
                this.dateheureField = value;
                this.RaisePropertyChanged("dateheure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateheureSpecified {
            get {
                return this.dateheureFieldSpecified;
            }
            set {
                this.dateheureFieldSpecified = value;
                this.RaisePropertyChanged("dateheureSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public player player1 {
            get {
                return this.player1Field;
            }
            set {
                this.player1Field = value;
                this.RaisePropertyChanged("player1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public player player2 {
            get {
                return this.player2Field;
            }
            set {
                this.player2Field = value;
                this.RaisePropertyChanged("player2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS/")]
    public partial class player : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nicknameField;
        
        private string passwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string passwd {
            get {
                return this.passwdField;
            }
            set {
                this.passwdField = value;
                this.RaisePropertyChanged("passwd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlayerData", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class PlayerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int playerID;
        
        public PlayerDataRequest() {
        }
        
        public PlayerDataRequest(int playerID) {
            this.playerID = playerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PlayerDataResponse", WrapperNamespace="http://WS/", IsWrapped=true)]
    public partial class PlayerDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WpfApplicationSysDis.ServiceReferenceWS.dataOut @return;
        
        public PlayerDataResponse() {
        }
        
        public PlayerDataResponse(WpfApplicationSysDis.ServiceReferenceWS.dataOut @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : WpfApplicationSysDis.ServiceReferenceWS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<WpfApplicationSysDis.ServiceReferenceWS.WSSoap>, WpfApplicationSysDis.ServiceReferenceWS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplicationSysDis.ServiceReferenceWS.helloResponse WpfApplicationSysDis.ServiceReferenceWS.WSSoap.hello(WpfApplicationSysDis.ServiceReferenceWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WpfApplicationSysDis.ServiceReferenceWS.helloRequest inValue = new WpfApplicationSysDis.ServiceReferenceWS.helloRequest();
            inValue.name = name;
            WpfApplicationSysDis.ServiceReferenceWS.helloResponse retVal = ((WpfApplicationSysDis.ServiceReferenceWS.WSSoap)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplicationSysDis.ServiceReferenceWS.helloResponse> WpfApplicationSysDis.ServiceReferenceWS.WSSoap.helloAsync(WpfApplicationSysDis.ServiceReferenceWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplicationSysDis.ServiceReferenceWS.helloResponse> helloAsync(string name) {
            WpfApplicationSysDis.ServiceReferenceWS.helloRequest inValue = new WpfApplicationSysDis.ServiceReferenceWS.helloRequest();
            inValue.name = name;
            return ((WpfApplicationSysDis.ServiceReferenceWS.WSSoap)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApplicationSysDis.ServiceReferenceWS.PlayerDataResponse WpfApplicationSysDis.ServiceReferenceWS.WSSoap.PlayerData(WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest request) {
            return base.Channel.PlayerData(request);
        }
        
        public WpfApplicationSysDis.ServiceReferenceWS.dataOut PlayerData(int playerID) {
            WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest inValue = new WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest();
            inValue.playerID = playerID;
            WpfApplicationSysDis.ServiceReferenceWS.PlayerDataResponse retVal = ((WpfApplicationSysDis.ServiceReferenceWS.WSSoap)(this)).PlayerData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApplicationSysDis.ServiceReferenceWS.PlayerDataResponse> WpfApplicationSysDis.ServiceReferenceWS.WSSoap.PlayerDataAsync(WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest request) {
            return base.Channel.PlayerDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApplicationSysDis.ServiceReferenceWS.PlayerDataResponse> PlayerDataAsync(int playerID) {
            WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest inValue = new WpfApplicationSysDis.ServiceReferenceWS.PlayerDataRequest();
            inValue.playerID = playerID;
            return ((WpfApplicationSysDis.ServiceReferenceWS.WSSoap)(this)).PlayerDataAsync(inValue);
        }
    }
}
